### ISSUE TITLE
[BUG] WiFi Changes do not work on Raspberry Pi

### ISSUE THREAD

**Issue by Tekunalogy** [DeepWaterExploration/DWE_OS_Legacy#14]
## Describe the bug

The following command used by DWE_OS for WiFi manager, fails in the Raspberry Pi OS.

```bash
nmcli --terse --fields active,ssid,bssid,mode,chan,freq,signal,security,wpa-flags,rsn-flags device wifi list
```

Network Manager is not running on RPi since [RPi uses the older `dhcpcd` by default](https://pimylifeup.com/raspberry-pi-network-manager/#:~:text=By%20default%2C%20the%20Raspberry%20Pi%20uses%20an%20older%20software%20called%20dhcpcd%20for%20its%20network%20handling.%20It%20is%20a%20bit%20more%20complicated%20to%20configure%20and%20has%20been%20superseded%20by%20Network%20Manager.).

## To Reproduce
- [Install Instructions followed here](https://docs.dwe.ai/software/driverUI.html#:~:text=You%20can%20install%20manually%20(for%20raspberry%20pi%20or%20other%20systems)%20with%20the%20following%20commands%3A)

## Expected behavior
DWE_OS should run on the host IP on port 5000.

## Screenshots
```bash
pi@raspberrypi:~/Documents/DWE_OS/ui $ sudo npm start

> @deepwaterexploration/dwe-controls@0.2.6 start
> node bin/index.js

Error: Command failed: nmcli --terse --fields active,ssid,bssid,mode,chan,freq,signal,security,wpa-flags,rsn-flags device wifi list
Error: NetworkManager is not running.

    at ChildProcess.exithandler (child_process.js:383:12)
    at ChildProcess.emit (events.js:400:28)
    at maybeClose (internal/child_process.js:1088:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:296:5) {
  killed: false,
  code: 8,
  signal: null,
  cmd: 'nmcli --terse --fields active,ssid,bssid,mode,chan,freq,signal,security,wpa-flags,rsn-flags device wifi list'
}
index.js

default command

Commands:
  index.js                      default command                        [default]
  index.js start [port] [host]  start the server
  index.js reset                reset the settings file

Options:
  --version  Show version number                                       [boolean]
  --help     Show help                                                 [boolean]

Error: Command failed: nmcli --terse --fields active,ssid,bssid,mode,chan,freq,signal,security,wpa-flags,rsn-flags device wifi list
Error: NetworkManager is not running.

    at ChildProcess.exithandler (child_process.js:383:12)
    at ChildProcess.emit (events.js:400:28)
    at maybeClose (internal/child_process.js:1088:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:296:5) {
  killed: false,
  code: 8,
  signal: null,
  cmd: 'nmcli --terse --fields active,ssid,bssid,mode,chan,freq,signal,security,wpa-flags,rsn-flags device wifi list'
}
^C^C^C^\Quit
```

## Environment (please complete the following information):
 - OS: Raspberry Pi OS

**Comment by Tekunalogy** [comment]
`iwlist wlan0 scan` can be used on RPi to list wifi devices
